# Generated by Django 6.0.3 on 2026-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_alter_program_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='program_videos/'),
        ),
        migrations.AddField(
            model_name='program',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
