# Generated by Django 5.2.13 on 2026-05-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_alter_enrollment_id_alter_exercise_id_and_more'),
        ('programs', '0011_alter_program_price'),
    ]

    operations = [
    ]
