# Generated by Django 5.2.13 on 2026-05-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_merge_20260514_1331'),
        ('programs', '0012_program_video_file_program_video_url'),
    ]

    operations = [
    ]
