# Generated by Django 5.2.13 on 2026-05-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_id'),
        ('payments', '0008_alter_payment_options_and_more'),
    ]

    operations = [
    ]
