# Generated by Django 5.2.13 on 2026-05-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_merge_20260514_1331'),
        ('payments', '0009_remove_unique_user_coach_payment'),
    ]

    operations = [
    ]
